In [1]:
import numpy as np

In [2]:
def swap(coords: np.ndarray):
    coords = coords.copy()

    x1 = coords[:, 0].copy()
    y1 = coords[:, 1].copy()
    x2 = coords[:, 2].copy()
    y2 = coords[:, 3].copy()

    coords[:, 0] = y1
    coords[:, 1] = x1
    coords[:, 2] = y2
    coords[:, 3] = x2

    return coords


coords = np.array([[10, 5, 15, 6, 0],
                   [11, 3, 13, 6, 0],
                   [5, 3, 13, 6, 1],
                   [4, 4, 13, 6, 1],
                   [6, 5, 13, 16, 1]])

swapped_coords = swap(coords)

print(swapped_coords)

[[ 5 10  6 15  0]
 [ 3 11  6 13  0]
 [ 3  5  6 13  1]
 [ 4  4  6 13  1]
 [ 5  6 16 13  1]]
